In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('student_mental_health_burnout.csv')

#Conhecendo os dados

display(df.head())
print(f'O df tem {df.shape[1]} Colunas e {df.shape[0]} Linhas')
print('\n')

#Percebe-se que algumas colunas como gender, stress_level, sleep_quality podem ser normalizadas por
#terem valores que são poucas classificações.

#Irei separar algumas colunas do tipo para analisá-las

colunas_analise = ['gender', 'course', 'year', 'stress_level', 'sleep_quality', 'internet_quality', 'burnout_level']

for coluna in colunas_analise:

    print(f'Feature : {coluna}')
    print(f'Número de Valores possíveis: {df[coluna].unique()}')
    print('\n')

#Como previsto, algumas colunas podem ser padronizadas
#Como os valores são strings e não há valores fora do padrão, nãos será necessário corrigir as strings.

,student_id,age,gender,course,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,financial_stress_score,social_support_score,physical_activity_hours,sleep_quality,attendance_percentage,cgpa,internet_quality,burnout_level
0,100001,23,Male,BTech,1st,4.3,6.8,6.1,High,10,3,4,2,6,1.8,Average,66.5,9.63,Good,High
1,100002,20,Male,BTech,3rd,1.4,4.7,3.0,High,2,10,8,5,9,1.9,Poor,55.8,6.04,Poor,Low
2,100003,24,Female,BCA,4th,3.7,4.8,1.5,Low,2,7,8,6,3,0.8,Good,85.0,8.31,Good,High
3,100004,21,Male,BSc,4th,1.6,6.7,7.0,High,3,3,4,9,9,0.7,Poor,89.1,5.95,Good,High
4,100005,23,Other,BSc,4th,2.0,6.7,5.4,High,7,7,6,4,4,1.7,Good,58.7,8.51,Good,Low

O df tem 20 Colunas e 150000 Linhas


Feature : gender
Número de Valores possíveis: <StringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str


Feature : course
Número de Valores possíveis: <StringArray>
['BTech', 'BCA', 'BSc', 'MBA', 'MCA', 'BBA']
Length: 6, dtype: str


Feature : year
Número de Valores possíveis: <StringArray>
['1st', '3rd', '4th', '2nd']
Length: 4, dtype: str


Feature : stress_level
Número de Valores possíveis: <StringArray>
['High', 'Low', 'Medium']
Length: 3, dtype: str


Feature : sleep_quality
Número de Valores possíveis: <StringArray>
['Average', 'Poor', 'Good']
Length: 3, dtype: str


Feature : internet_quality
Número de Valores possíveis: <StringArray>
['Good', 'Poor', 'Average']
Length: 3, dtype: str


Feature : burnout_level
Número de Valores possíveis: <StringArray>
['High', 'Low', 'Medium']
Length: 3, dtype: str

In [ ]:
#Tratando os dados
# OBS: ESSE CODIGO LEVA MUITO TEMPO, FOI ERRO MEU, AQUELE FOR PERCORRE A LISTA MUITAS VEZES
# A melhor função pra isso é o factorize, faz exatamente o que eu queria

def obter_valor(arr, v):
    #Função que irá transformar as str em números
    novo_arr = list(arr)
    return novo_arr.index(v)

for coluna in colunas_analise:
    # Itera pelas colunas, e a aplica a função em cada uma delas
    df[coluna] = df[coluna].apply( lambda x : obter_valor(df[coluna].unique(), x))

#Visualizando como o df está agora:

display(df.head())

In [32]:
print(pd.factorize(df['gender']))
print('\n')
#Essa função retorna uma tupla, os valores codificados e os valores unicos, em ordem.

for coluna in colunas_analise:

    df[coluna] = pd.factorize(df[coluna])[0]
    #Como queremos apenas os codigos, usa-se [0]
    
#Visualizando os dados tratados:

display(df.head())
print('\n')

#Como student_id não impacta, podemos retirar a coluna

df = df.drop(columns=['student_id'])

# Agora, podemos dividir o dataset e formar os dados e o target

y_data = df['burnout_level']
x_data = df.drop(columns=['burnout_level'])

print('Dados Gerais: ')
display(x_data)
print('\n')
print('Resultados: ')
print(y_data)

(array([0, 0, 1, ..., 0, 0, 0], shape=(150000,)), Index(['Male', 'Female', 'Other'], dtype='str'))

,student_id,age,gender,course,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,financial_stress_score,social_support_score,physical_activity_hours,sleep_quality,attendance_percentage,cgpa,internet_quality,burnout_level
0,100001,23,0,0,0,4.3,6.8,6.1,0,10,3,4,2,6,1.8,0,66.5,9.63,0,0
1,100002,20,0,0,1,1.4,4.7,3.0,0,2,10,8,5,9,1.9,1,55.8,6.04,1,1
2,100003,24,1,1,2,3.7,4.8,1.5,1,2,7,8,6,3,0.8,2,85.0,8.31,0,0
3,100004,21,0,2,2,1.6,6.7,7.0,0,3,3,4,9,9,0.7,1,89.1,5.95,0,0
4,100005,23,2,2,2,2.0,6.7,5.4,0,7,7,6,4,4,1.7,2,58.7,8.51,0,1

Dados Gerais:

,age,gender,course,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,financial_stress_score,social_support_score,physical_activity_hours,sleep_quality,attendance_percentage,cgpa,internet_quality
0,23,0,0,0,4.3,6.8,6.1,0,10,3,4,2,6,1.8,0,66.5,9.63,0
1,20,0,0,1,1.4,4.7,3.0,0,2,10,8,5,9,1.9,1,55.8,6.04,1
2,24,1,1,2,3.7,4.8,1.5,1,2,7,8,6,3,0.8,2,85.0,8.31,0
3,21,0,2,2,1.6,6.7,7.0,0,3,3,4,9,9,0.7,1,89.1,5.95,0
4,23,2,2,2,2.0,6.7,5.4,0,7,7,6,4,4,1.7,2,58.7,8.51,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,24,1,2,1,1.6,8.2,11.3,2,9,9,5,3,10,2.0,2,54.2,7.82,0
149996,25,0,1,1,9.9,4.8,1.6,0,10,3,10,10,2,0.1,1,53.6,7.19,2
149997,22,0,0,0,1.4,4.4,4.6,0,10,8,6,4,7,1.6,2,90.7,9.78,2
149998,19,0,2,1,1.5,4.3,1.1,2,8,6,5,7,4,1.1,0,83.9,9.88,2
149999,20,0,4,1,3.7,6.6,2.6,2,5,1,5,7,6,1.8,2,89.8,7.00,1

Resultados:
0         0
1         1
2         0
3         0
4         1
         ..
149995    1
149996    0
149997    0
149998    2
149999    0
Name: burnout_level, Length: 150000, dtype: int64